package com.project.nearby.models;


import lombok.Getter;
import lombok.Setter;
import org.springframework.stereotype.Component;

@Getter
@Setter
@Component
public class Tags {
    private String addrCity;
    private String addrCountry;
    private String addrHousenumber;
    private String addrPostcode;
    private String addrStreet;
    private String amenity;
    private String building;
    private String phone;
    private String tourism;
    private String name;
    private String indoorSeating;
    private String outdoorSeating;
    private String nameKn;
    private String smoking;
    private String checkDate;
    private String cuisine;
    private String level;
    private String operator;
    private String toilets;
    private String toiletsWheelchair;
    private String wheelchair;
    private String rastorant;
    private String openingHours;
    private String delivery;
    private String takeaway;
    private String buildingLevels;
    private String roofLevels;
    private String internetAccess;
    private String shop;
    private String roofColour;
    private String website;
    private String addrFloor;
    private String bar;
    private String branch;
    private String brand;
    private String capacity;
    private String dietVegetarian;
    private String dietPescetarian;
    private String nameEn;
    private String contactMobile;
    private String contactPhone;
    private String airConditioning;
    private String microbrewery;
    private String brandWikidata;
    private String sourceAddrHousenumber;
    private String description;
    private String address;
    private String driveThrough;
    private String reservation;
    private String toiletsPosition;
    private String note;
    private String operationalStatus;
    private String paymentCreditCards;
    private String paymentDebitCards;
    private String buildingLevelsUnderground;
    private String roofShape;
    private String internetAccessFee;
    private String internetAccessSsid;
    private String addrHamlet;
    private String addrSuburb;
    private String email;
    private String source;
    private String minAge;
    private String access;
    private String operatorType;
    private String brandKs;
    private String brandPa;
    private String brandUr;
    private String brandWikipedia;
    private String nameKs;
    private String namePa;
    private String nameUr;
    private String craft;
    private String addrDistrict;
    private String contactInstagram;
    private String altName;
    private String createdBy;
    private String dietNonVegetarian;
    private String food;
    private String officialName;
    private String startDate;
    private String wikidata;
    private String paymentMastercard;
    private String paymentVisa;
    private String addrHousename;
    private String shortName;
    private String wikimediaCommons;
    private String wikipedia;
    private String speciality;
    private String addrFull;
    private String addrState;
    private String fax;
    private String dietHalal;
    private String highchair;
    private String paymentCash;
    private String paymentUpi;
    private String dietVegan;
    private String happycowId;
    private String oldName;
    private String officialNamePa;
    private String officialNameUr;
    private String wifi;
    private String brandWikipediaPa;
    private String brandWikipediaUr;
    private String designation;
    private String phone1;
    private String phone2;
    private String intName;
    private String checkDateDietHalal;
    private String surveyDate;
    private String userDefined;
    private String contactWhatsapp;
    private String cuisine1;
    private String contactFacebook;
    private String nameHi;
    private String working;
    private String service;
    private String coffee;
    private String drinkCoffee;
    private String drinkJuice;
    private String addrStreet1;
    private String brewery;
    private String contactEmail;
    private String contactWebsite;
    private String driveIn;
    private String organic;
    private String amenity1;
    private String refVatin;
    private String nameMl;
    private String mapillary;
    private String nameZh;
    private String dietLactoVegetarian;
    private String addrPlace;
    private String ele;
    private String paymentElectronicPurses;
    private String floor;
    private String mobile;
    private String openingHoursCovid19;
    private String dineIn;
    private String dietPlantBased;
    private String dietMeat;
    private String paymentBitcoincash;
    private String dietSeafood;
    private String image;
    private String brandDe;
    private String brandFr;
    private String nameDe;
    private String nameFr;
    private String checkDateSmoking;
    private String fixme;
    private String contactPinterest;
    private String addrNumber;
    private String checkDateOpeningHours;
    private String openingHoursSigned;
    private String addrUnit;
    private String contactTwitter;
    private String toiletsAccess;
    private String contactYoutube;
    private String buildingFloor;
    private String realFire;
    private String cafe;
    private String paymentCards;
    private String nameKo;


    private String id;

    private String buildingPart;
    private String government;
    private String height;
    private String layer;


    private String nameTe;
    private String office;

    private String roofMaterial;

    private String type;
}
